### ISSUE TITLE
Backend code | CognitoHelper service

### ISSUE THREAD

**Issue by asishap007** [james-ingold/cognito-mfa-email-example#1]
Hi James

Am trying to understanding the custom auth flow using cognito mentioned in your article. 
https://jamesingold.com/amazon-cognito-mfa-with-email-lambda-triggers
Here CognitoHelper service mentioned, but not able to see the details in the post.
Could you please share the repo link of backend code ?

**Comment by james-ingold** [comment]
Hey there, thanks for checking out the blog. The backend part of the post is psuedo code. For implementing the SRP_A string value with Cognito in Nodejs the CognitoHelper referenced in the post would be pretty close to https://github.com/borisirota/amazon-user-pool-srp-client/blob/master/index.js. 

This is also a good answer on the matter: 
https://stackoverflow.com/questions/41115639/aws-cognito-user-authentication-missing-required-parameter-srp-a/41155990#41155990
